version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: location-api
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - location-network

  app:
    build: .
    ports:
      - "3006:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - location-network

networks:
  location-network:
    driver: bridge

volumes:
  pgdata:
