version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: location-api
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - location-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: location-api
    volumes:
      - .:/usr/src/app
    networks:
      - location-network

networks:
  location-network:
    driver: bridge

