version: '3.9'

volumes:
  data:
    driver: local

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - '5432'
    ports:
        - 5432:5432