name: remis-Backend CI checks
on:
  push:
    branches:
      - main
      - master
      - staging
  pull_request:
    branches:
      - main
      - master
      - staging

env:
  NODE_OPTIONS: '--max_old_space_size=8192'
  NODE_ENV: local
  PORT: 3000
  JWT_SECRET_KEY: OHJqa1ly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Specify the Node.js version here
          cache: 'yarn'

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
  
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start PostgreSQL service
        run: |
          cp .env.test .env
          docker-compose --env-file .env.test up -d db

      - name: Wait for PostgreSQL to be ready
        run: docker-compose exec -T db bash -c 'until pg_isready; do sleep 1; done'

      - name: Run unit tests
        run: yarn test:e2e