name: remis-Backend CI checks
on:
  push:
    branches:
      - main
      - master
      - staging
  pull_request:
    branches:
      - main
      - master
      - staging

env:
  NODE_OPTIONS: '--max_old_space_size=8192'
  NODE_ENV: test
  PORT: 3000
  # Database configuration
  DB_HOST: db
  DB_PORT: 5432
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_NAME: location-api
  DB_SYNC: true
  JWT_SECRET: your_jwt_secret
  JWT_EXPIRATION: 1h

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: location-api
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h db -p 5432 -U postgres; do
            sleep 1
          done

      - name: Run lint
        run: yarn lint

      - name: Run unit tests
        env:
          DB_HOST: db
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: location-api
        run: yarn test:e2e